# Generated by Django 4.2.28 on 2026-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service', models.CharField(choices=[('lawn-mowing', 'Lawn Mowing'), ('garden-maintenance', 'Garden Maintenance'), ('hedge-trimming', 'Hedge Trimming'), ('weed-control', 'Weed Control'), ('waste-removal', 'Waste Removal'), ('custom-landscaping', 'Custom Landscaping / Other')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_service_date', models.DateField(blank=True, help_text='For future CRM reminders', null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
